### ISSUE TITLE
Function to segment raw data

### ISSUE THREAD

**Issue by joynjosh** [halam189/Gait_Recognition_LSTM#1]
Could you share function to segment raw data?

**Comment by halam189** [comment]
Hello, thank you for your interest.

I used the Matlab code for reading the raw data, then, splitting the raw data into gait segments.
Please check the codes in: https://github.com/halam189/Gait_Recognition_LSTM/tree/main/FeaEx_Matlab
It depends on the experimental settings and the dataset that you should run one of the below scripts:
- A_GaitSignalsExtraction_WHU_iden.m
- A_GaitSignalsExtraction_WHU_auth.m
- A_GaitSignalsExtraction_OU_iden.m
- A_GaitSignalsExtraction_OU_auth_520_225.m
To run the code, you need Matlab installed, and place the dataset in an appropriate path (specified by "dataPath" in the code).

Best regards.

**Comment by joynjosh** [comment]
Thank you for your reply, 
the following function is not available?
-funcProcessingExtract
-func_DataReArrange

**Comment by halam189** [comment]
Hello, thank you for your feedback.
I added the "func_DataReArrange". Please find https://github.com/halam189/Gait_Recognition_LSTM/blob/main/FeaEx_Matlab/func_DataReArrange.m
I also updated the code (removing the add_path("func_DataReArrange"). This line is not important.
Thanks again,
Best regards,

**Comment by joynjosh** [comment]
Thank you,  it works. However seems that it only for windows segment. how about gait cycle segment? could you also share for the gait cycle segment?

**Comment by halam189** [comment]
Hello, This study does not segment gait data into gait cycles.
We used window-based approach for segmentation.
Although section IV.C.2 reports a comparison between cycle-based and window-based segmentation, the cycles we used were from the [study](https://ieeexplore.ieee.org/abstract/document/9056812) (Dataset#1). And, we do not have their code to obtain such gait cycles.
